PaseosEcologicos.Management/PaseosEcologicos.Web/Controllers/TiposDeServiciosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PaseosEcologicos.Model;

namespace PaseosEcologicos.Web.Controllers
{   
    public class TiposDeServiciosController : Controller
    {
        private PaseosEcologicosEntities context = new PaseosEcologicosEntities();

        //
        // GET: /TiposDeServicios/

        public ViewResult Index()
        {
            return View(context.Tipos_De_Servicios.Include(tipos_de_servicios => tipos_de_servicios.Servicios).ToList());
        }

        //
        // GET: /TiposDeServicios/Details/5

        public ViewResult Details(int id)
        {
            Tipos_De_Servicios tipos_de_servicios = context.Tipos_De_Servicios.Single(x => x.Id == id);
            return View(tipos_de_servicios);
        }

        //
        // GET: /TiposDeServicios/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /TiposDeServicios/Create

        [HttpPost]
        public ActionResult Create(Tipos_De_Servicios tipos_de_servicios)
        {
            if (ModelState.IsValid)
            {
                context.Tipos_De_Servicios.Add(tipos_de_servicios);
                context.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(tipos_de_servicios);
        }
        
        //
        // GET: /TiposDeServicios/Edit/5
 
        public ActionResult Edit(int id)
        {
            Tipos_De_Servicios tipos_de_servicios = context.Tipos_De_Servicios.Single(x => x.Id == id);
            return View(tipos_de_servicios);
        }

        //
        // POST: /TiposDeServicios/Edit/5

        [HttpPost]
        public ActionResult Edit(Tipos_De_Servicios tipos_de_servicios)
        {
            if (ModelState.IsValid)
            {
                context.Entry(tipos_de_servicios).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipos_de_servicios);
        }

        //
        // GET: /TiposDeServicios/Delete/5
 
        public ActionResult Delete(int id)
        {
            Tipos_De_Servicios tipos_de_servicios = context.Tipos_De_Servicios.Single(x => x.Id == id);
            return View(tipos_de_servicios);
        }

        //
        // POST: /TiposDeServicios/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Tipos_De_Servicios tipos_de_servicios = context.Tipos_De_Servicios.Single(x => x.Id == id);
            context.Tipos_De_Servicios.Remove(tipos_de_servicios);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PaseosEcologicos.Management/PaseosEcologicos.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Mantenimientos Paseos Ecologicos</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                @* <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")*@
                <div class="logo text-warning">
                    <span class="P">Paseos</span>
                    <span class="E">Ecologicos</span>
                </div>
                @*</p>*@
            </div>
            <style>
                .logo {
                    position: relative;
                }

                    .logo .P, .logo .E {
                        float: left;
                        font-size: 35px;
                    }

                    .logo .P {
                        font-family: fantasy;
                        /*color: rgba(0, 173, 49, 0.44);*/
                    }

                    .logo .E {
                        /*color: rgba(9, 117, 0, 0.57);*/
                    }
            </style>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul id="menu">
                            <li>@Html.ActionLink("Clientes", "Index", "Clientes")</li>
                            <li>@Html.ActionLink("Tipos de Servicios", "Index", "TiposDeServicios")</li>
                            <li>@Html.ActionLink("Servicios", "Index", "Servicios")</li>
                            <li>@Html.ActionLink("Implementos", "Index", "Implementos")</li>
                            <li>@Html.ActionLink("Paseos", "Index", "Paseos")</li>
                        </ul>   
                    }
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - Paseos Ecologicos | Por: Leomaris Reyes, Juan Acosta y Anthony Del Rosario.</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>