PaseosEcologicos.Management/PaseosEcologicos.Web/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PaseosEcologicos.Model;

namespace PaseosEcologicos.Web.Controllers
{   
    public class ClientesController : Controller
    {
        private PaseosEcologicosEntities context = new PaseosEcologicosEntities();

        //
        // GET: /Clientes/

        public ViewResult Index()
        {
            return View(context.Clientes.Include(clientes => clientes.Clientes1).Include(clientes => clientes.Reservaciones).Include(clientes => clientes.Servicios_Consumidos).ToList());
        }

        //
        // GET: /Clientes/Details/5

        public ViewResult Details(int id)
        {
            Clientes clientes = context.Clientes.Single(x => x.Id == id);
            return View(clientes);
        }

        //
        // GET: /Clientes/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Clientes/Create

        [HttpPost]
        public ActionResult Create(Clientes clientes)
        {
            if (ModelState.IsValid)
            {
                context.Clientes.Add(clientes);
                context.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(clientes);
        }
        
        //
        // GET: /Clientes/Edit/5
 
        public ActionResult Edit(int id)
        {
            Clientes clientes = context.Clientes.Single(x => x.Id == id);
            return View(clientes);
        }

        //
        // POST: /Clientes/Edit/5

        [HttpPost]
        public ActionResult Edit(Clientes clientes)
        {
            if (ModelState.IsValid)
            {
                context.Entry(clientes).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clientes);
        }

        //
        // GET: /Clientes/Delete/5
 
        public ActionResult Delete(int id)
        {
            Clientes clientes = context.Clientes.Single(x => x.Id == id);
            return View(clientes);
        }

        //
        // POST: /Clientes/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Clientes clientes = context.Clientes.Single(x => x.Id == id);
            context.Clientes.Remove(clientes);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PaseosEcologicos.Management/PaseosEcologicos.Web/Controllers/ServiciosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PaseosEcologicos.Model;

namespace PaseosEcologicos.Web.Controllers
{   
    public class ServiciosController : Controller
    {
        private PaseosEcologicosEntities context = new PaseosEcologicosEntities();

        //
        // GET: /Servicios/

        public ViewResult Index()
        {
            return View(context.Servicios.Include(servicios => servicios.Implementos).Include(servicios => servicios.Servicios_Consumidos).ToList());
        }

        //
        // GET: /Servicios/Details/5

        public ViewResult Details(int id)
        {
            Servicios servicios = context.Servicios.Single(x => x.Id == id);
            return View(servicios);
        }

        //
        // GET: /Servicios/Create

        public ActionResult Create()
        {

            var tipos = context.Tipos_De_Servicios;
            ViewBag.TipoId = new SelectList(tipos, "Id", "Titulo");
            return View();
        } 

        //
        // POST: /Servicios/Create

        [HttpPost]
        public ActionResult Create(Servicios servicios)
        {
            if (ModelState.IsValid)
            {
                context.Servicios.Add(servicios);
                context.SaveChanges();
                return RedirectToAction("Index");  
            }

            var tipos = context.Tipos_De_Servicios;
            ViewBag.TipoId = new SelectList(tipos, "Id", "Titulo");
            return View(servicios);
        }
        
        //
        // GET: /Servicios/Edit/5
 
        public ActionResult Edit(int id)
        {
            Servicios servicios = context.Servicios.Single(x => x.Id == id);
            var tipos = context.Tipos_De_Servicios;
            ViewBag.TipoId = new SelectList(tipos, "Id", "Titulo");
            return View(servicios);
        }

        //
        // POST: /Servicios/Edit/5

        [HttpPost]
        public ActionResult Edit(Servicios servicios)
        {
            if (ModelState.IsValid)
            {
                context.Entry(servicios).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            var tipos = context.Tipos_De_Servicios;
            ViewBag.TipoId = new SelectList(tipos, "Id", "Titulo");
            return View(servicios);
        }

        //
        // GET: /Servicios/Delete/5
 
        public ActionResult Delete(int id)
        {
            Servicios servicios = context.Servicios.Single(x => x.Id == id);
            return View(servicios);
        }

        //
        // POST: /Servicios/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Servicios servicios = context.Servicios.Single(x => x.Id == id);
            context.Servicios.Remove(servicios);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PaseosEcologicos.Management/PaseosEcologicos.Web/Views/Clientes/Create.cshtml
@model PaseosEcologicos.Model.Clientes

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Clientes</legend>

		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PaseosEcologicos.Management/PaseosEcologicos.Web/Views/Clientes/Delete.cshtml
@model PaseosEcologicos.Model.Clientes

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Clientes</legend>

    <div class="display-label">AfiliadorId</div>
    <div class="display-field">@Model.AfiliadorId</div>

    <div class="display-label">Nombre</div>
    <div class="display-field">@Model.Nombre</div>

    <div class="display-label">Apellido</div>
    <div class="display-field">@Model.Apellido</div>

    <div class="display-label">Celular</div>
    <div class="display-field">@Model.Celular</div>

    <div class="display-label">Correo</div>
    <div class="display-field">@Model.Correo</div>

    <div class="display-label">Clientes1</div>
    <div class="display-field">@(Model.Clientes1 == null ? "None" : Model.Clientes1.Count.ToString())</div>

    <div class="display-label">Clientes2</div>
    <div class="display-field">@Html.DisplayTextFor(_ => Model.Clientes2).ToString()</div>

    <div class="display-label">Reservaciones</div>
    <div class="display-field">@(Model.Reservaciones == null ? "None" : Model.Reservaciones.Count.ToString())</div>

    <div class="display-label">Servicios_Consumidos</div>
    <div class="display-field">@(Model.Servicios_Consumidos == null ? "None" : Model.Servicios_Consumidos.Count.ToString())</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PaseosEcologicos.Management/PaseosEcologicos.Web/Views/Clientes/Index.cshtml
@model IEnumerable<PaseosEcologicos.Model.Clientes>

@{
    ViewBag.Title = "Index";
}

<h2>Clientes</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th></th>
        <th>Nombre
        </th>
        <th>Apellido
        </th>
        <th>Celular
        </th>
        <th>Correo
        </th>
        <th>Servicios Consumidos
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Detalle", "Details", new { id = item.Id })
           
            </td>
            <td>
                @item.Nombre
            </td>
            <td>
                @item.Apellido
            </td>
            <td>
                @item.Celular
            </td>
            <td>
                @item.Correo
            </td>
            <td>
                <ul>
                    @foreach (var servicio in item.Servicios_Consumidos)
                    {
                        <li>@Html.ActionLink(servicio.Servicios.Titulo.ToString(), "Details", "Servicios", new {id = servicio.ServicioId}, new {})</li>
                    }
                </ul>

            </td>
        </tr>
    }

</table>

PaseosEcologicos.Management/PaseosEcologicos.Web/Views/Clientes/_CreateOrEdit.cshtml
@model PaseosEcologicos.Model.Clientes

@* This partial view defines form fields that will appear when creating and editing entities *@

@*<div class="editor-label">
    @Html.LabelFor(model => model.AfiliadorId)
</div>
<div class="editor-field form-group">
    @Html.EditorFor(model => model.AfiliadorId)
    @Html.ValidationMessageFor(model => model.AfiliadorId)
</div>*@

<div class="editor-label">
    @Html.LabelFor(model => model.Nombre)
</div>
<div class="editor-field form-group">
    @Html.EditorFor(model => model.Nombre)
    @Html.ValidationMessageFor(model => model.Nombre)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.Apellido)
</div>
<div class="editor-field form-group">
    @Html.EditorFor(model => model.Apellido)
    @Html.ValidationMessageFor(model => model.Apellido)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.Celular)
</div>
<div class="editor-field form-group">
    @Html.EditorFor(model => model.Celular)
    @Html.ValidationMessageFor(model => model.Celular)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.Correo)
</div>
<div class="editor-field form-group">
    @Html.EditorFor(model => model.Correo)
    @Html.ValidationMessageFor(model => model.Correo)
</div>